### ISSUE TITLE
failed to use global session when cached socket is closed

### ISSUE THREAD

**Issue by levimm** [casbin/mongodb-adapter#16]
I'm using this mongo adapter for a while and sometimes when network is reconnect, I got "Closed explicitly" error.
After digging in, I find this adapter using the global session to do all the operation. When the cache socket is closed, it won't restore the session.
I'd like to create a pr to fix this issue. There're two solutions. First continues using this global session but checks session status in a goroutine to refresh it. Second uses session.Copy() for all db operation. Not sure which one is better. Any advise?

**Comment by hsluoyz** [comment]
Hi @levimm , why not rebuild the connection if the socket is closed? I mean if the socket is found closed, there would be an error, then we reconnect to get the session back. I think this way works the best?

**Comment by levimm** [comment]
@hsluoyz I'll create another pr according to your suggestion.

**Comment by levimm** [comment]
@hsluoyz Could you check the pr #17 . It doesn't need to handle the different cases of error and add the retry logic. A few more sockets will be used but they'll be closed eventually.

**Comment by tokingHong** [comment]
I have encountered  the same problem that my adapter will fail to load policy after I restart my MongoDB. @hsluoyz @levimm

**Comment by tokingHong** [comment]
> I have encountered the same problem that my adapter will fail to load policy after I restart my MongoDB. @hsluoyz @levimm

I use the synced enforcer to reload automatically.

**Comment by tokingHong** [comment]
@hsluoyz   请问是Chinese小哥吗。我英文太差了，请问上面这个问题是否有解决。我看casbin也是您维护的是吧。之前提了一个错误的问题还没close的U•ェ•*U

**Comment by hsluoyz** [comment]
Merged.

**Comment by hsluoyz** [comment]
@tokingHong In that issue (https://github.com/casbin/casbin/issues/191), I asked about a minimized working example, not still not provided yet.

**Comment by hsluoyz** [comment]
This issue can be closed now.
