### ISSUE TITLE
Using official MongoDB driver

### ISSUE THREAD

**Issue by akrantz01** [casbin/mongodb-adapter#21]
Are there any plans to move from mgo to the official [MongoDB Driver](https://docs.mongodb.com/ecosystem/drivers/go/)? Seeing as it is officially supported by the MongoDB engineers, I think it would be a good idea. The migration guide can be found [here](https://www.mongodb.com/blog/post/go-migration-guide).

**Comment by hsluoyz** [comment]
Sorry for the late response. I think this is a very good idea. Can anyone make a PR about it?

**Comment by akrantz01** [comment]
Oh, no worries. I attempted to re-write it using the official driver around the time I first made this issue but ran into some problems with indexes. I'm not super familiar with MongoDB like I can use it for its most basic functionality, but after that, I'm pretty much clueless.

**Comment by hsluoyz** [comment]
@akrantz01 can you see if this PR works? https://github.com/casbin/mongodb-adapter/pull/22

**Comment by hsluoyz** [comment]
Fixed in: https://github.com/casbin/mongodb-adapter/issues/21
