### ISSUE TITLE
existing rules are not checked on first AddPolicy call

### ISSUE THREAD

**Issue by Dodu17** [casbin/mongodb-adapter#26]
I have discovered a bug using the mongo adapter. When the main function is called twice the first AddPolicy did not recognize, that the rule already exists and after the second main call the same rule is present in the db twice.
```go
func main() {
	a, _ := mongodbadapter.NewAdapter("mongodb://localhost:27017/dev-permission")
	e, _ := casbin.NewEnforcer("./assets/authorization_model.casbin", a)
	e.EnableAutoSave(true)

	ok, _ := e.Enforce("alice", "/media/:id", "GET")
	// 1. main call: ok == false -> correct
	// 2. main call: ok == true -> correct

	ok, _ = e.AddPolicy("alice", "/media/:id", "GET")
	// 1. main call: ok == true -> correct
	// 2. main call: ok == true -> incorrect

	ok, _ = e.Enforce("alice", "/media/:id", "GET")
	// 1. main call: ok == true  -> correct
	// 2. main call: ok == true  -> correct

	ok, _ = e.AddPolicy("alice", "/media/:id", "GET")
	// 1. main call: ok == false -> correct
	// 2. main call: ok == false -> correct
}
```

Now I have the same db entry twice in my collection. So i adjusted the main function and discovered another bug:
```go
func main() {
	a, _ := mongodbadapter.NewAdapter("mongodb://localhost:27017/dev-permission")
	e, _ := casbin.NewEnforcer("./assets/authorization_model.casbin", a)
	e.EnableAutoSave(true)

	ok, _ := e.Enforce("alice", "/media/:id", "GET")
	// ok == true -> correct

	ok, _ = e.RemovePolicy("alice", "/media/:id", "GET")
	// ok == false -> incorrect, because one rule was deleted from the db
}
```

Now I'm calling the main function two more times (second and third call)
On second call I have the same behavior as at first call, because there is still one rule in the db
After this second call also the second rule was removed, so on that on the third call the Enforce returns false, which is basically correct at this point.

**Comment by hsluoyz** [comment]
@nodece @GopherJ @dovics @00LT00 can anyone take this issue?

**Comment by nodece** [comment]
It looks the code is correct,  please provide the Casbin version.

**Comment by hsluoyz** [comment]
@00LT00 please take this issue.

**Comment by 00LT00** [comment]
Thanks for your reports.We will find out the reason as soon as possible.

**Comment by Dodu17** [comment]
> It looks the code is correct, please provide the Casbin version.

go.mod:

	github.com/casbin/casbin/v2 v2.8.2
	github.com/casbin/mongodb-adapter/v2 v2.1.0

**Comment by arshadrk** [comment]
Any Update on this issue or any temporary work for this issue??

**Comment by hsluoyz** [comment]
I didn't understand this issue.

```go
ok, _ := e.Enforce("alice", "/media/:id", "GET")
	// 1. main call: ok == false -> correct
	// 2. main call: ok == true -> correct
```

What does this mean?

**Comment by 00LT00** [comment]
The first and the second call main function. In the first, e.enforce is false. @hsluoyz

**Comment by hsluoyz** [comment]
@Dodu17 @arshadrk can you debug why the adapter doesn't recognize the existing rule in the 2nd run?

**Comment by hsluoyz** [comment]
@00LT00 plz also help to debug it.

**Comment by arshadrk** [comment]
@hsluoyz @00LT00 This issue will be fixed on using V3.0.0.But as the tagged release 3.0.0 's go.mod file contains the module as "module github.com/casbin/mongodb-adapter/v2" we can't update that to 3.0.0. The change in mod file version is available in master , it would be better if that change is moved under the tag 3.0.0.

**Comment by hsluoyz** [comment]
@arshadrk can you make a PR to update the "module github.com/casbin/mongodb-adapter/v2" dependency to 3.0.0?

**Comment by arshadrk** [comment]
This is already done in [PR31](https://github.com/casbin/mongodb-adapter/pull/31).

**Comment by hsluoyz** [comment]
Fixed in: https://github.com/casbin/mongodb-adapter/pull/31#issuecomment-702004980
