### ISSUE TITLE
why not set unique index?

### ISSUE THREAD

**Issue by lxzan** [casbin/mongodb-adapter#27]

**Comment by hsluoyz** [comment]
@lxzan can you make a PR to fix it?

**Comment by hsluoyz** [comment]
Released v3.0.0: https://github.com/casbin/mongodb-adapter/releases/tag/v3.0.0

**Comment by alexferl** [comment]
@hsluoyz can the go module be updated for this? It's still on v2.

**Comment by hsluoyz** [comment]
@alexferl good point! Can you help make a PR to fix it? Thanks.
