### ISSUE TITLE
panic when  use AddRolesForUser API

### ISSUE THREAD

**Issue by lbbwyt** [casbin/mongodb-adapter#33]
![image](https://user-images.githubusercontent.com/13368145/95813984-cee8be80-0d4b-11eb-96cf-7802885f009c.png)

this adapter cannot convert to "persist.BatchAdapter"

**Comment by hsluoyz** [comment]
@lbbwyt This is because this adapter doesn't implement the BatchAdapter interface. Please make a PR like this to implement it: https://github.com/casbin/casbin-pg-adapter/pull/6

**Comment by hsluoyz** [comment]
Closed as stale.
