### ISSUE TITLE
Is a persist.BatchAdapter planed?

### ISSUE THREAD

**Issue by Dodu17** [casbin/mongodb-adapter#35]
Currently it's not possible to use addPolicies or removePolicies because of not providing a constructor for persist.BatchAdapter.

Will it be added in the future to the mongo-adapter, or is a BatchAdapter not planed?

**Comment by hsluoyz** [comment]
@yyellowsun can you take this issue?

**Comment by yyellowsun** [comment]
> Currently it's not possible to use addPolicies or removePolicies because of not providing a constructor for persist.BatchAdapter.
> 
> Will it be added in the future to the mongo-adapter, or is a BatchAdapter not planed?

@Dodu17 It will be added in the future.I wil try to implement it this weekend.You can also make a PR to implement it.
