### ISSUE TITLE
mongodbadapter.adapter is not persist.BatchAdapter

### ISSUE THREAD

**Issue by QVllasa** [casbin/mongodb-adapter#37]
When I try to call AddPolicies on *Enforcer, I get the following error:  

panic: interface conversion: *mongodbadapter.adapter is not persist.BatchAdapter: missing method AddPolicies

Currently using: 	
"github.com/casbin/casbin/v2"
"github.com/casbin/mongodb-adapter/v3"

**Comment by hsluoyz** [comment]
@QVllasa please use latest v3.1.0: https://github.com/casbin/mongodb-adapter/releases/tag/v3.1.0

**Comment by QVllasa** [comment]
Thanks a lot! Works now perfectly.
