### ISSUE TITLE
Random empty response

### ISSUE THREAD

**Issue by berayb** [casbin/mongodb-adapter#51]
When we add new policy and ask a list after that, we randomly get empty response first ~10mins. 

When we wait some time, it works without any issue. 

We are testing with MongoDB Atlas Sandbox. 

What could be the problem? Thanks in advance.

**Comment by hsluoyz** [comment]
@JalinWang 

/cc @tangyang9464

**Comment by JalinWang** [comment]
@berayb 
After adding, you can inspect the database and see if it has been added.
How about adding policies to the database manually and seeing if the first request of querying delays?
