### ISSUE TITLE
Do we need to .SavePolicy?

### ISSUE THREAD

**Issue by mukill** [casbin/mongodb-adapter#56]
What is the point of using .SavePolicy when Add, Update, and Remove all seem to save the new lines to the db?

**Comment by imp2002** [comment]
The enforcer is in memory, do `savePolicy()` save to DB for persistence. If you don't need persistence, don't do `savePolicy()`

**Comment by mukill** [comment]
@imp2002 it looks like we save to the db on each CUD action though from reading the source code? Isn't it redundant to also call save policy?

**Comment by hsluoyz** [comment]
@mukill if your adapter supports Auto-Save, then you don't need to manually call SavePolicy(), see: https://casbin.io/docs/adapters#autosave
